LearnLatin/Models/ManageViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LearnLatin.Models.ManageViewModels
{ 
    public class EditViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

LearnLatin/Models/TrueOutOfFalseTask.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LearnLatin.Models
{
    public class TrueOutOfFalseTask
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public String Description { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public ApplicationUser Creator { get; set; }
        public ApplicationUser Editor { get; set; }
        public Test Test { get; set; }
        public Int32 NumInQueue { get; set; }
        public ICollection<TrueOutOfFalseAnswer> Answers { get; set; }
        public Boolean IsAnsweredRight { get; set; }
       
    }
}

LearnLatin/Controllers/TrueOutOfFalseTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LearnLatin.Data;
using LearnLatin.Models;
using LearnLatin.Models.CreateViewModels;
using Microsoft.AspNetCore.Identity;
using LearnLatin.Models.EditViewModels;
using LearnLatin.Models.ViewModels;

namespace LearnLatin.Controllers
{
    public class TrueOutOfFalseTasksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public TrueOutOfFalseTasksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: TrueOutOfFalseTasks
        public async Task<IActionResult> Index()
        {
            return View(await _context.TrueOutOfFalseTasks.ToListAsync());
        }

        // GET: TrueOutOfFalseTasks/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trueOutOfFalseTask = await _context.TrueOutOfFalseTasks
                .Include(t => t.Test)
                .Include(t => t.Creator)
                .Include(t => t.Editor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trueOutOfFalseTask == null)
            {
                return NotFound();
            }
            ViewBag.Test = trueOutOfFalseTask.Test; 
            return View(trueOutOfFalseTask);
        }

        public async Task<IActionResult> Display(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.TrueOutOfFalseTasks
                .Include(t => t.Test)
                .Include(t => t.Answers)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (task == null)
            {
                return NotFound();
            }

            var taskView = new TaskViewModel
            {
                Id = task.Id,
                TestId = task.Test.Id,
                Description = task.Description,
                Answers = task.Answers
            };

            return View(taskView);
        }

        // GET: TrueOutOfFalseTasks/Create
        public async Task<IActionResult> Create(Guid testId)
        {
            if (testId == null)
            {
                return this.NotFound();
            }

            var test = await this._context.Tests
                .SingleOrDefaultAsync(x => x.Id == testId);

            if (test == null)
            {
                return this.NotFound();
            }

            this.ViewBag.Test = test;
            return this.View(new TaskCreateViewModel());
        }

        // POST: TrueOutOfFalseTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid testId, TaskCreateViewModel model)
        {
            if (testId == null)
            {
                return this.NotFound();
            }

            var test = await this._context.Tests
                .Include(t => t.Tasks)
                .SingleOrDefaultAsync(x => x.Id == testId);

            if (test == null)
            {
                return this.NotFound();
            }

            var user = await this._userManager.GetUserAsync(this.HttpContext.User);

            if (this.ModelState.IsValid)
            {
                var task = new TrueOutOfFalseTask
                {
                    Test = test,
                    Description = model.Description,
                    Created = DateTime.Now,
                    Creator = user
                };

                if (test.NumOfTasks == null)
                {
                    task.NumInQueue = 1;
                    test.NumOfTasks = 1;
                }
                else
                {
                    task.NumInQueue = (Int32)test.NumOfTasks + 1;
                    test.NumOfTasks++;
                }
                this._context.Add(task);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "Tests", new { id = task.Test.Id });
            }
            this.ViewBag.Test = test;
            return View(model);
        }

        // GET: TrueOutOfFalseTasks/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await this._context.TrueOutOfFalseTasks
                .Include(t => t.Test)
                .SingleOrDefaultAsync(x => x.Id == id);

            if (task == null)
            {
                return NotFound();
            }
            var model = new TaskEditViewModel
            {
                Description = task.Description
            };
            ViewBag.Task = task;
            ViewBag.Test = task.Test;
            return View(task);
        }

        // POST: TrueOutOfFalseTasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, TaskEditViewModel model)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await this._context.TrueOutOfFalseTasks
                .Include(x => x.Test)
                .SingleOrDefaultAsync(x => x.Id == id);

            if (task == null)
            {
                return NotFound();
            }

            var user = await this._userManager.GetUserAsync(this.HttpContext.User);

            if (ModelState.IsValid)
            {
                task.Description = model.Description;
                task.Modified = DateTime.Now;
                task.Editor = user;

                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "Tests", new { id = task.Test.Id });
            }
            this.ViewBag.Test = task.Test;
            return View(task);
        }

        // GET: TrueOutOfFalseTasks/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trueOutOfFalseTask = await _context.TrueOutOfFalseTasks
                .Include(t => t.Test)
                .Include(t => t.Creator)
                .Include(t => t.Editor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trueOutOfFalseTask == null)
            {
                return NotFound();
            }
            ViewBag.Test = trueOutOfFalseTask.Test;
            return View(trueOutOfFalseTask);
        }

        // POST: TrueOutOfFalseTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var trueOutOfFalseTask = await _context.TrueOutOfFalseTasks
                .Include(t => t.Test)
                .FirstOrDefaultAsync(m => m.Id == id);
            trueOutOfFalseTask.Test.NumOfTasks--;
            _context.TrueOutOfFalseTasks.Remove(trueOutOfFalseTask);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrueOutOfFalseTaskExists(Guid id)
        {
            return _context.TrueOutOfFalseTasks.Any(e => e.Id == id);
        }

    }
}

LearnLatin/Views/TrueOutOfFalseTasks/Create.cshtml
@model LearnLatin.Models.CreateViewModels.TaskCreateViewModel

@{
    ViewData["Title"] = "Создать таск со выбором ответа";
}

<h1>Создать таск</h1>

<h4>Тип: выбор правильного ответа</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-testId="@ViewBag.Test.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Tests" asp-route-id="@ViewBag.Test.Id">Назад к таску</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LearnLatin/Views/TrueOutOfFalseTasks/Delete.cshtml
@model LearnLatin.Models.TrueOutOfFalseTask

@{
    ViewData["Title"] = "Удалить таск с выбором ответа";
}

<h1>Удалить таск</h1>

<h3>Вы уверены, что хотите удалить этот таск?</h3>
<div>
    <h6>Тип: выбор правильного ответа</h6>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Задание
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Создано
        </dt>
        <dd class="col-sm-10">
            @Model.Creator.UserName (@Model.Created)
        </dd>
        @if (Model.Editor != null)
        {
            <dt class="col-sm-2">
                Редактировано
            </dt>
            <dd class="col-sm-10">
                @Model.Editor.UserName (@Model.Modified)
            </dd>
        }
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Details" asp-controller="Tests" asp-route-id="@ViewBag.Test.Id">Назад к таску</a>
    </form>
</div>

LearnLatin/Views/TrueOutOfFalseTasks/Details.cshtml
@model LearnLatin.Models.TrueOutOfFalseTask

@{
    ViewData["Title"] = "Детали таска с выбором ответа";
}

<h1>Детали таска</h1>

<div>
    <h6>Тип: выбор правильного ответа</h6>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Задание
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Создано
        </dt>
        <dd class="col-sm-10">
            @Model.Creator.UserName (@Model.Created)
        </dd>
        @if (@Model.Editor != null)
        {
            <dt class="col-sm-2">
                Редактировано
            </dt>
            <dd class="col-sm-10">
                @Model.Editor.UserName (@Model.Modified)               
            </dd>
        }
        </dl>
        
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a> |
    <a asp-action="Details" asp-controller="Tests" asp-route-id="@ViewBag.Test.Id">Назад</a>
</div>

LearnLatin/Views/TrueOutOfFalseTasks/Display.cshtml
@model LearnLatin.Models.ViewModels.TaskViewModel

<div class="container">
    @using (Html.BeginForm("SaveResults", "Tests"))
    {
        <div class="row">
            <div class="col-6 text-center">
                <h2>Вопрос</h2>
                <a style="width:70%; border-color: #4b1ebb;border-width: 3px;" class="btn text-center">@Model.Description</a>
            </div>
            <div class="col-6">
                <h2 class="text-center">Ответ</h2>
                @foreach (var item in Model.Answers)
                {
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio" name="userAnswerId"
                                   value="@item.Id" asp-for="@item.AnsValue" /> @item.AnsValue
                        </label>
                    </div>
                }
            </div>
        </div>


        <div class="row mt-4">
            @*<div class="col-6">
                    <button type="button" class="btn btn-primary text-center">Завершить тренировку</button>
                </div>*@
            <div class="col-6 text-right">
                <input type="hidden" name="taskId" value="@Model.Id" />
                <input type="hidden" name="testId" value="@Model.TestId" />
                <input type="submit" class="btn btn-primary text-center" value="Дальше" />
            </div>
        </div>
    }
</div>

LearnLatin/Views/TrueOutOfFalseTasks/Edit.cshtml
@model LearnLatin.Models.TrueOutOfFalseTask

@{
    ViewData["Title"] = "Редактировать таск с выбором ответа";
}

<h1>Редактировать таск</h1>

<h4>Тип: выбор правильного ответа</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label">Задание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Tests" asp-route-id="@ViewBag.Test.Id">Назад к таску</a> |
    <a asp-action="Details" asp-controller="TrueOutOfFalseTasks" asp-route-id="@ViewBag.Task.Id">К деталям таска</a><br />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LearnLatin/Views/TrueOutOfFalseTasks/Index.cshtml
@model IEnumerable<LearnLatin.Models.TrueOutOfFalseTask>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modified)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumInQueue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumInQueue)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>