LearnLatin/Models/ManageViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LearnLatin.Models.ManageViewModels
{ 
    public class EditViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

LearnLatin/Models/Theme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LearnLatin.Models
{
    public class Theme
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public String Name { get; set; }
        public String Description { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public ApplicationUser Creator { get; set; }
        public ApplicationUser Editor { get; set; }
        public ICollection<Test> Tests { get; set; }
        public Int32? NumOfTests { get; set; }
        public Guid? ParentThemeId { get; set; }
        public Theme ParentTheme { get; set; }
        public ICollection<Theme> Children { get; set; }
        public ICollection<TheoryBlock> TheoryBlocks { get; set; }
    }
}

LearnLatin/Models/ViewModels/ThemeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LearnLatin.Models.ViewModels
{
    public class ThemeViewModel
    {
        public Theme Theme { get; set; }
        public UserTheme UserTheme { get; set; }
        public ICollection<TheoryBlock> TheoryBlocks { get; set; }
    }
}

LearnLatin/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LearnLatin.Data;
using LearnLatin.Models;
using Microsoft.AspNetCore.Identity;
using LearnLatin.Models.CreateViewModels;
using LearnLatin.Models.EditViewModels;

namespace LearnLatin.Controllers
{
    public class TestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public TestsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Tests
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tests
                .Include(t => t.Creator)
                .Include(t => t.Editor)
                .ToListAsync());
        }

        // GET: Tests/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Tests
                .Include(t => t.Creator)
                .Include(t => t.Editor)
                .Include(t => t.Tasks)
                .ThenInclude(x => x.Answers)
                .Include(t => t.Tasks)
                .ThenInclude(x => x.Creator)
                .Include(t => t.InputTasks)
                .ThenInclude(x => x.Answers)
                .Include(t => t.InputTasks)
                .ThenInclude(x => x.Creator)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }
        public async Task<IActionResult> Start(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Tests
                .Include(t => t.Tasks)
                .ThenInclude(t => t.Answers)
                .Include(t => t.InputTasks)
                .ThenInclude(t => t.Answers)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (test == null || test.NumOfTasks == null)
            {
                return RedirectToAction("Index", "PersonalArea");
            }

            int taskCounter = 0;
            foreach (var item in test.Tasks)
            {
                if (item.Answers.Count > 1)
                {
                    taskCounter++;
                }
            }
            int inTaskCounter = 0;
            foreach (var item in test.InputTasks)
            {
                if (item.Answers.Count > 0)
                {
                    inTaskCounter++;
                }
            }

            if (taskCounter != test.Tasks.Count || inTaskCounter != test.InputTasks.Count)
            {
                return RedirectToAction("Index", "PersonalArea");
            }

            test.NumOfRightAnswers = null;
            foreach (var item in test.Tasks)
            {
                item.IsAnsweredRight = false;
            }
            foreach (var item in test.InputTasks)
            {
                item.IsAnsweredRight = false;
            }
            await this._context.SaveChangesAsync();

            foreach (var item in test.Tasks)
            {
                if (item.NumInQueue == 1)
                {
                    return RedirectToAction("Display", "TrueOutOfFalseTasks", new { id = item.Id });
                }
            }
            foreach (var item in test.InputTasks)
            {
                if (item.NumInQueue == 1)
                {
                    return RedirectToAction("Display", "InputTasks", new { id = item.Id });
                }
            }

            return View();
        }

        // GET: Tests/Create
        public IActionResult Create()
        {
            return View(new TestCreateViewModel());
        }

        // POST: Tests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TestCreateViewModel model)
        {
            var user = await this._userManager.GetUserAsync(this.HttpContext.User);

            if (this.ModelState.IsValid)
            {
                var test = new Test
                {
                    Name = model.Name,
                    Description = model.Description,
                    Created = DateTime.Now,
                    Creator = user,
                    Editor = user,
                    Modified = DateTime.Now,
                    NumOfTasks = 0
                };

                this._context.Add(test);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Index", "PersonalArea");
            }
            return View(model);
        }

        // GET: Tests/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Tests.FindAsync(id);
            if (test == null)
            {
                return NotFound();
            }
            var model = new TestEditViewModel
            {
                Name = test.Name,
                Description = test.Description
            };
            return View(model);
        }

        // POST: Tests/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, TestEditViewModel model)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Tests
                .FirstOrDefaultAsync(m => m.Id == id);

            if (test == null)
            {
                return NotFound();
            }

            var user = await this._userManager.GetUserAsync(this.HttpContext.User);

            if (ModelState.IsValid)
            {
                test.Name = model.Name;
                test.Description = model.Description;
                test.Modified = DateTime.Now;
                test.Editor = user;

                await this._context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Tests/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Tests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // POST: Tests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var test = await _context.Tests.FindAsync(id);
            _context.Tests.Remove(test);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestExists(Guid id)
        {
            return _context.Tests.Any(e => e.Id == id);
        }

        public async Task<IActionResult> SaveResults(Guid? testId, Guid taskId, Guid userAnswerId, String userInputAnswer)
        {
            if (testId == null)
            {
                return NotFound();
            }

            var test = await _context.Tests
                .Include(t => t.InputTasks)
                .Include(t => t.Tasks)
                .FirstOrDefaultAsync(m => m.Id == testId);

            if (test == null)
            {
                return NotFound();
            }

            if (taskId == null)
            {
                return NotFound();
            }
            var trueOutOfFalseTask = await _context.TrueOutOfFalseTasks
                .Include(t => t.Test)
                .ThenInclude(t => t.Theme)
                .FirstOrDefaultAsync(m => m.Id == taskId);

            var inputTask = await _context.InputTasks
                .Include(i => i.Answers)
                .Include(t => t.Test)
                .ThenInclude(t => t.Theme)
                .FirstOrDefaultAsync(m => m.Id == taskId);



            if (trueOutOfFalseTask != null)
            {
                var userAnswer = await _context.TrueOutOfFalseAnswers
                    .FirstOrDefaultAsync(m => m.Id == userAnswerId);

                if (userAnswer.IsTrue && trueOutOfFalseTask.NumInQueue == 1)
                {
                    test.NumOfRightAnswers = 1;
                    trueOutOfFalseTask.IsAnsweredRight = true;
                }
                else if (userAnswer.IsTrue)
                {
                    test.NumOfRightAnswers++;
                    trueOutOfFalseTask.IsAnsweredRight = true;
                }

                await _context.SaveChangesAsync();

                if (trueOutOfFalseTask.NumInQueue == trueOutOfFalseTask.Test.NumOfTasks) // если таск последний в очереди
                {
                    // if for the first time
                    if (test.IsNotForTheFirstTime)
                    {
                        return RedirectToAction("Edit", "UserTests", new { testId = test.Id });
                    }
                    else
                    {
                        return RedirectToAction("Create", "UserTests", new { testId = test.Id });
                    }
                   
                    // return RedirectToAction("Edit", "UserTests", new { testId = test.Id });

LearnLatin/Views/Themes/AddTest.cshtml
@model LearnLatin.Models.CreateViewModels.TestAddViewModel
@{
    ViewData["Title"] = "Добавить тест";
}

<h1>Добавить тест</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddTest">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="TestId" class="col-md-2 control-label">Тест</label>
                    <div class="col-md-10">
                        <select asp-for="TestId" class="form-control" asp-items="ViewBag.TestId"></select>
                    </div>
                </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Themes" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LearnLatin/Views/Themes/Create.cshtml
@model LearnLatin.Models.CreateViewModels.ThemeCreateViewModel

@{
    ViewData["Title"] = "Создать тему";
}

<h1>Создать тему</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @if (ViewBag.ThemeId != null)
            {
                <div class="form-group">
                    <label asp-for="ParentThemeId" class="col-md-2 control-label">Родительская тема</label>
                    <div class="col-md-10">
                        <select asp-for="ParentThemeId" class="form-control" asp-items="ViewBag.ThemeId"></select>
                    </div>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LearnLatin/Views/Themes/Delete.cshtml
@model LearnLatin.Models.Theme

@{
    ViewData["Title"] = "Удаление";
}

<h1>Удалить</h1>

<h3>Вы уверены, что хотите удалить эту тему?</h3>
<div>
    <h4>Тема</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Название
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Описание
        </dt>
        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Создано
        </dt>
        <dd class="col-sm-10">
            @Model.Creator.UserName
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class="col-sm-2">
            Редактировано
        </dt>
        <dd class="col-sm-10">
            @Model.Editor.UserName
            @Html.DisplayFor(model => model.Modified)
        </dd>
        <dt class="col-sm-2">
            Количество тестов
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumOfTests)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

LearnLatin/Views/Themes/Details.cshtml
@model LearnLatin.Models.ViewModels.ThemeViewModel

@{
    ViewData["Title"] = "Детали темы";
}

<h1>Тема: @Model.Theme.Name</h1>
<hr />
<h3>@Model.Theme.Description</h3>

<h6>Прогресс:</h6>
<div class="progress mt-1">    
    @if(Model.UserTheme != null)
    {
        <input type="hidden" name="progress" value="@Model.UserTheme.Progress" />
    }  
    <div class="progress-bar" id="progressPerc" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
</div>


<div>
    @if (User.IsInRole("Administrators"))
    {
        <dt class="col-sm-2">
            Создано
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Theme.Created)
        </dd>
        <dt class="col-sm-2">
            Редактировано
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Theme.Modified)
        </dd>
        <dt class="col-sm-2">
            Количество тестов
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Theme.NumOfTests)
        </dd>
    }
</div>

<h2>Теоретические блоки:</h2>

<div class="panel panel-default">
    <table class="table table-striped">
        <tbody>
            @foreach (var item in Model.TheoryBlocks)
            {
            <tr>
                <td class="border-dark">
                    <h3>@item.Name</h3>
                    <div>
                        @item.Text
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>





<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Тесты
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Theme.Tests)
            {
                <tr>
                    <td>
                        @if (User.IsInRole("Administrators"))
                        {
                            <a asp-action="Details" asp-controller="Tests" asp-route-id="@item.Id">
                                @item.Name
                            </a>
                            <a class="btn btn-primary text-center mr-3"
                               asp-area="" asp-controller="Tests" asp-action="Start" asp-route-id="@item.Id">
                                Пройти тест
                            </a>
                        }
                        else
                        {
                            <a>
                                @item.Name
                            </a>
                            <a class="btn btn-primary text-center mr-3"
                               asp-area="" asp-controller="Tests" asp-action="Start" asp-route-id="@item.Id">
                                Пройти тест
                            </a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    @if (User.IsInRole("Administrators"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Theme.Id">Редактировать тему</a> <span> | </span>
        <a asp-action="Create" asp-controller="TheoryBlocks" asp-route-id="@Model.Theme.Id">Добавить теоретический блок</a> <span> | </span>
        <a asp-action="AddTest" asp-controller="Themes" asp-route-id="@Model.Theme.Id">Добавить тест</a> <span> | </span>
    }

    <a asp-action="Index" asp-controller="PersonalArea">Назад</a>
</div>

LearnLatin/Views/Themes/Edit.cshtml
@model LearnLatin.Models.CreateViewModels.ThemeCreateViewModel
@{
    ViewData["Title"] = "Редактировать тему";
}

<h1>Редактировать тему</h1>

<h4>Тема</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentThemeId" class="col-md-2 control-label">Родительская тема</label>
                <div class="col-md-10">
                    <select asp-for="ParentThemeId" class="form-control" asp-items="ViewBag.ThemeId"></select>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LearnLatin/Views/Themes/Index.cshtml
@model IEnumerable<LearnLatin.Models.Theme>

@{
    ViewData["Title"] = "Темы";
}

<h1>Темы</h1>

<p>
    <a asp-action="Create">Добавить тему</a>
</p>

<div class="panel panel-default">
    <table class="table table-striped">
        <tbody>
            @foreach (var item in Model.OrderBy(x => x.Name))
            {
                @if (item.Name != "Root")
                {
                    <tr>
                        <td>
                            <h3><a asp-action="Details" asp-route-id="@item.Id" style="font-size: 1em">@item.Name</a></h3><br />
                            @item.Description<br />

                            @if (item.ParentTheme != null)
                            {
                                <p>Родительская тема: @item.ParentTheme.Name</p>
                            }
                            <div class="p-2"><i>Создан: @item.Creator.UserName @item.Created</i></div>
                        </td>
                        <td class="align-middle" style="min-width: 90px;">
                            @item.NumOfTests тестов<br />
                            @if (User.IsInRole("Administrators"))
                            {
                                <a asp-action="Create" asp-controller="TheoryBlocks" asp-route-id="@item.Id">Добавить теоретический блок</a><br />
                                <a asp-action="AddTest" asp-controller="Themes" asp-route-id="@item.Id">Добавить тест</a>
                            }
                        </td>

                        @if (item.Editor != null)
                        {
                            <td>
                                <i>
                                    Редактировано:<br />
                                    @item.Editor.UserName<br />
                                    @item.Modified
                                </i>
                            </td>
                        }

                        <td class="align-middle" style="min-width: 70px;">
                            <a asp-action="Edit" asp-route-id="@item.Id">
                                <i data-toggle="tooltip" data-title="Редактировать" class="fas fa-pencil-alt fa-lg text-muted hand_cursor"></i>
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.Id">
                                <i data-toggle="tooltip" data-title="Удалить" class="fas fa-trash-alt fa-lg text-danger hand_cursor"></i>
                            </a>
                        </td>
                    </tr>


                }
            }
        </tbody>
    </table>
</div>